/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace/index'
import { Route as AuthenticatedWorkspaceGraphRouteImport } from './routes/_authenticated/workspace/graph'
import { Route as AuthenticatedWorkspaceConfigurationIndexRouteImport } from './routes/_authenticated/workspace/configuration/index'
import { Route as AuthenticatedWorkspaceConfigurationToolsRouteImport } from './routes/_authenticated/workspace/configuration/tools'
import { Route as AuthenticatedWorkspaceConfigurationSettingsRouteImport } from './routes/_authenticated/workspace/configuration/settings'
import { Route as AuthenticatedWorkspaceConfigurationOntologyRouteImport } from './routes/_authenticated/workspace/configuration/ontology'
import { Route as AuthenticatedWorkspaceConfigurationAboutRouteImport } from './routes/_authenticated/workspace/configuration/about'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceGraphRoute =
  AuthenticatedWorkspaceGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfigurationIndexRoute =
  AuthenticatedWorkspaceConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfigurationToolsRoute =
  AuthenticatedWorkspaceConfigurationToolsRouteImport.update({
    id: '/configuration/tools',
    path: '/configuration/tools',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfigurationSettingsRoute =
  AuthenticatedWorkspaceConfigurationSettingsRouteImport.update({
    id: '/configuration/settings',
    path: '/configuration/settings',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfigurationOntologyRoute =
  AuthenticatedWorkspaceConfigurationOntologyRouteImport.update({
    id: '/configuration/ontology',
    path: '/configuration/ontology',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceConfigurationAboutRoute =
  AuthenticatedWorkspaceConfigurationAboutRouteImport.update({
    id: '/configuration/about',
    path: '/configuration/about',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/workspace/graph': typeof AuthenticatedWorkspaceGraphRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/configuration/about': typeof AuthenticatedWorkspaceConfigurationAboutRoute
  '/workspace/configuration/ontology': typeof AuthenticatedWorkspaceConfigurationOntologyRoute
  '/workspace/configuration/settings': typeof AuthenticatedWorkspaceConfigurationSettingsRoute
  '/workspace/configuration/tools': typeof AuthenticatedWorkspaceConfigurationToolsRoute
  '/workspace/configuration/': typeof AuthenticatedWorkspaceConfigurationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/workspace/graph': typeof AuthenticatedWorkspaceGraphRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/configuration/about': typeof AuthenticatedWorkspaceConfigurationAboutRoute
  '/workspace/configuration/ontology': typeof AuthenticatedWorkspaceConfigurationOntologyRoute
  '/workspace/configuration/settings': typeof AuthenticatedWorkspaceConfigurationSettingsRoute
  '/workspace/configuration/tools': typeof AuthenticatedWorkspaceConfigurationToolsRoute
  '/workspace/configuration': typeof AuthenticatedWorkspaceConfigurationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/_authenticated/workspace/graph': typeof AuthenticatedWorkspaceGraphRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/workspace/configuration/about': typeof AuthenticatedWorkspaceConfigurationAboutRoute
  '/_authenticated/workspace/configuration/ontology': typeof AuthenticatedWorkspaceConfigurationOntologyRoute
  '/_authenticated/workspace/configuration/settings': typeof AuthenticatedWorkspaceConfigurationSettingsRoute
  '/_authenticated/workspace/configuration/tools': typeof AuthenticatedWorkspaceConfigurationToolsRoute
  '/_authenticated/workspace/configuration/': typeof AuthenticatedWorkspaceConfigurationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspace'
    | '/workspace/graph'
    | '/workspace/'
    | '/workspace/configuration/about'
    | '/workspace/configuration/ontology'
    | '/workspace/configuration/settings'
    | '/workspace/configuration/tools'
    | '/workspace/configuration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspace/graph'
    | '/workspace'
    | '/workspace/configuration/about'
    | '/workspace/configuration/ontology'
    | '/workspace/configuration/settings'
    | '/workspace/configuration/tools'
    | '/workspace/configuration'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/workspace'
    | '/_authenticated/workspace/graph'
    | '/_authenticated/workspace/'
    | '/_authenticated/workspace/configuration/about'
    | '/_authenticated/workspace/configuration/ontology'
    | '/_authenticated/workspace/configuration/settings'
    | '/_authenticated/workspace/configuration/tools'
    | '/_authenticated/workspace/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/graph': {
      id: '/_authenticated/workspace/graph'
      path: '/graph'
      fullPath: '/workspace/graph'
      preLoaderRoute: typeof AuthenticatedWorkspaceGraphRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuration/': {
      id: '/_authenticated/workspace/configuration/'
      path: '/configuration'
      fullPath: '/workspace/configuration/'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfigurationIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuration/tools': {
      id: '/_authenticated/workspace/configuration/tools'
      path: '/configuration/tools'
      fullPath: '/workspace/configuration/tools'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfigurationToolsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuration/settings': {
      id: '/_authenticated/workspace/configuration/settings'
      path: '/configuration/settings'
      fullPath: '/workspace/configuration/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfigurationSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuration/ontology': {
      id: '/_authenticated/workspace/configuration/ontology'
      path: '/configuration/ontology'
      fullPath: '/workspace/configuration/ontology'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfigurationOntologyRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/configuration/about': {
      id: '/_authenticated/workspace/configuration/about'
      path: '/configuration/about'
      fullPath: '/workspace/configuration/about'
      preLoaderRoute: typeof AuthenticatedWorkspaceConfigurationAboutRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceGraphRoute: typeof AuthenticatedWorkspaceGraphRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
  AuthenticatedWorkspaceConfigurationAboutRoute: typeof AuthenticatedWorkspaceConfigurationAboutRoute
  AuthenticatedWorkspaceConfigurationOntologyRoute: typeof AuthenticatedWorkspaceConfigurationOntologyRoute
  AuthenticatedWorkspaceConfigurationSettingsRoute: typeof AuthenticatedWorkspaceConfigurationSettingsRoute
  AuthenticatedWorkspaceConfigurationToolsRoute: typeof AuthenticatedWorkspaceConfigurationToolsRoute
  AuthenticatedWorkspaceConfigurationIndexRoute: typeof AuthenticatedWorkspaceConfigurationIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceGraphRoute: AuthenticatedWorkspaceGraphRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
    AuthenticatedWorkspaceConfigurationAboutRoute:
      AuthenticatedWorkspaceConfigurationAboutRoute,
    AuthenticatedWorkspaceConfigurationOntologyRoute:
      AuthenticatedWorkspaceConfigurationOntologyRoute,
    AuthenticatedWorkspaceConfigurationSettingsRoute:
      AuthenticatedWorkspaceConfigurationSettingsRoute,
    AuthenticatedWorkspaceConfigurationToolsRoute:
      AuthenticatedWorkspaceConfigurationToolsRoute,
    AuthenticatedWorkspaceConfigurationIndexRoute:
      AuthenticatedWorkspaceConfigurationIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
